#! /bin/sh -e

. /usr/share/debconf/confmodule

DEF=/etc/default/huawei-wmi/

if [ "$1" = configure ]
then
	db_get huawei-wmi/users
	users=$RET
	db_stop

	groupadd --system huawei-wmi 2> /dev/null || true
	for user in $users
	do
		usermod --append --groups huawei-wmi "$user"
	done

	mkdir --parents --mode=02775 $DEF
	chgrp huawei-wmi $DEF
fi

#DEBHELPER#
