#! /bin/sh -e

readonly DEF=/etc/default/huawei-wmi/
readonly WMI=/sys/devices/platform/huawei-wmi/

readonly CCT=charge_control_thresholds
readonly DCT=charge_thresholds
readonly FLS=fn_lock_state
readonly KLT=kbdlight_timeout
readonly PUL=power_unlock

available() {
	[ \( -e "$WMI$CCT" -o -e "$WMI$DCT" \) -a -e "$WMI$FLS" ]
}

available || sleep 1
available || {
	echo No Huawei WMI available >&2
	exit 1
}

for wmi_xct in "$WMI$CCT" "$WMI$DCT"; do
	if [ -e "$wmi_xct" ]; then
		readonly cct=$(basename "$wmi_xct")
	else
		readonly dct=$(basename "$wmi_xct")
	fi
done

[ "$cct" -a "$dct" -a "$cct" != "$dct" ]
