#! /bin/sh -e

. /usr/lib/huawei-wmi/available

[ -e "$DEF$dct" ] && mv --force -- "$DEF$dct" "$DEF$cct"

[ -e "$DEF$cct" ] || cp -- "$WMI$cct" "$DEF"
chmod g=u -- "$DEF$cct"

chgrp huawei-wmi -- "$WMI$cct" "$WMI$FLS"
chmod g=u -- "$WMI$cct" "$WMI$FLS"

if [ -e "$WMI$KLT" ]
then
	chgrp huawei-wmi -- "$WMI$KLT"
	chmod g=u -- "$WMI$KLT"
fi

if [ -e "$WMI$PUL" ]
then
	chgrp huawei-wmi -- "$WMI$PUL"
	chmod g=u -- "$WMI$PUL"
fi
