#! /bin/sh -e

. /usr/lib/huawei-wmi/constants

[ -e $WMI$CCT -a -e $WMI$FLS ] || sleep 1

[ -e $WMI$CCT -a -e $WMI$FLS ] || {
	echo >&2 "No Huawei WMI available"
	exit 1
}

if [ -e $DEF$CCT ]
then
	wmi_cct=$(basename $WMI$CCT)
	for def_cct in $DEF$CCT
	do
		[ $(basename $def_cct) = $wmi_cct ] || mv --force $def_cct $DEF$wmi_cct
	done
else
	cp $WMI$CCT $DEF
	chmod g=u $DEF$CCT
fi

chgrp huawei-wmi $WMI$CCT $WMI$FLS
chmod g=u $WMI$CCT $WMI$FLS
